# ./docker-compose.yml
# Local, reproducible Postgres with relative mounts (safe to share).

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/London
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql:ro        # SQL files (read-only)
      - ./data:/data:ro      # CSVs (read-only)
      - ./exports:/exports   # CSV exports out of the DB (writeable)

volumes:
  pgdata:
